export const CATEGORIES = [
  'Groceries',
  'Food & Drink',
  'Transport',
  'Travel',
  'Fitness',
  'Health',
  'Shopping',
  'Entertainment',
  'Rent & Housing',
  'Loans & Finance',
  'Home & Utilities',
  'Subscriptions',
  'Software & Cloud',
  'Personal Care',
  'Education',
  'Gifts',
  'Other',
] as const